<?php

declare(strict_types=1);

use Magento\Contact\ViewModel\UserDataProvider;
use Magento\Framework\Escaper;
use MageMonk\ContactUs\Block\Form;

/**
 * @var Form $block
 * @var Escaper $escaper
 * @var UserDataProvider $viewModel
 */

$viewModel = $block->getViewModel();
?>
<form class="form contact"
      action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      x-data="{showForm : false}">
    <?= $block->getChildHtml('contact.form.types') ?>
    <div class="contact-container" x-show="showForm">
        <div class="contact-container-inner">
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $escaper->escapeHtml(__('Write Us')) ?></span></legend>
                <br/>
                <div class="field name">
                    <label class="label" for="name"><span><?= $escaper->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name"
                               id="name"
                               title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                               value="<?= $escaper->escapeHtmlAttr($viewModel->getUserName()) ?>"
                               class="form-input w-full"
                               type="text"]
                               required/>
                    </div>
                </div>
                <div class="field email">
                    <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="email"
                               id="email"
                               title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                               value="<?= $escaper->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                               class="form-input w-full"
                               type="email"
                               required/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone">
                        <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <div class="control">
                        <input name="telephone"
                               id="telephone"
                               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                               value="<?= $escaper->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                               class="form-input w-full"
                               type="tel"/>
                    </div>
                </div>
                <div class="field comment">
                    <label class="label" for="comment">
                        <span><?= $escaper->escapeHtml(__('What’s on your mind?')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="comment"
                                  id="comment"
                                  title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                                  class="form-input w-full"
                                  cols="5"
                                  rows="6"
                                  required
                        ><?= $escaper->escapeHtml($viewModel->getUserComment()) ?></textarea>
                    </div>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
                <?= $block->getBlockHtml('formkey') ?>
                <div class="actions-toolbar"
                     data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value=""/>
                        <button type="submit"
                                title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>"
                                class="action submit primary">
                            <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
            <?= $block->getChildHtml('contact.content.right') ?>
        </div>
    </div>
</form>
