<?php

/** @var $block Magento\Framework\View\Element\Template */
?>

<!-- ko scope: 'customer-contact' -->
    <!-- ko if: isLoggedIn -->
    <li>
        <a data-bind="text: getLabel(), attr: { href: getContactUrl() }"></a>
    </li>
    <!-- /ko -->
<!-- /ko -->

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
